# -*- coding: utf-8 -*-
"""project4_Healthcare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPoutBJkz2aIKJWw0f-A5ER06WJJHgqP
"""

import pandas as pd
import numpy as np

df = pd.read_csv("Hospital_ER_Data.csv")
df.head()

df.tail()

df.shape

df.info()

df.describe()

df.describe(include='object')

df.columns

df.dtypes

df.isnull().sum()

#df.isnull().mean()*100

df.isnull().mean()*100
df.head(20)

df.duplicated().sum()

df.dtypes

df["Patient Admission Date"] = pd.to_datetime(df["Patient Admission Date"])

df.dtypes

df["Admission Year"] = df["Patient Admission Date"].dt.year

df["Admission Month"] = df["Patient Admission Date"].dt.month
df["Admission Month Name"] = df["Patient Admission Date"].dt.month_name()

df["Admission Quarter"] = df["Patient Admission Date"].dt.quarter

df["Admission Day"] = df["Patient Admission Date"].dt.day
df["Admission Day Name"] = df["Patient Admission Date"].dt.day_name()

df["Admission Week"] = df["Patient Admission Date"].dt.isocalendar().week

df["Weekend"] = np.where(
    df["Patient Admission Date"].dt.dayofweek >= 5,
    "Weekend",
    "Weekday"
)
df.head()

df["Patient Gender"].unique()



#df["Doctor"].unique()

df["Department Referral"].unique()

df["Patient First Inital"].unique()

df["Patient Admission Flag"].unique()

# Detect Negative Values(Numeric)
numeric_columns = df.select_dtypes(include=np.number).columns

for col in numeric_columns:
    print(col)
    print((df[col] < 0).sum())

# Outlier
numeric_columns = df.select_dtypes(include=np.number).columns

for col in numeric_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"{col}: {len(outliers)} outliers")

df["Patient Gender"] = df["Patient Gender"].str.strip()

df["Patient Gender"] = df["Patient Gender"].str.title()

df.head()

df.to_csv(
    "cleaned_healthcare_data.csv",
    index=False
)

